services:
  - type: web
    name: maize-leaf-anomaly-detection
    runtime: python
    pythonVersion: 3.11.9
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ALLOW_ORIGINS
        value: http://localhost:8000
